# Generated by Django 3.2.6 on 2022-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heart',
            old_name='trestbps',
            new_name='restbps',
        ),
        migrations.AlterField(
            model_name='heart',
            name='cp',
            field=models.CharField(choices=[(1, 'Atypical angina'), (2, 'Typical angina'), (3, 'Asymptomatic'), (4, 'Non-anginal pain')], max_length=20),
        ),
        migrations.AlterField(
            model_name='heart',
            name='exang',
            field=models.CharField(choices=[(0, 'Yes'), (1, 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='heart',
            name='fbs',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='heart',
            name='restecg',
            field=models.CharField(choices=[(0, 'Normal'), (1, 'ST'), (2, 'Hypertrophy')], default='Normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.CharField(choices=[(1, 'Male'), (0, 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='heart',
            name='slope',
            field=models.CharField(choices=[(1, 'Up Sloping'), (2, 'Flat'), (3, 'Down Sloping')], max_length=15),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.CharField(choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversible Defect')], max_length=20),
        ),
    ]
