# Generated by Django 3.2.6 on 2022-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0002_auto_20220605_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default='Male', max_length=10),
        ),
    ]
