# Generated by Django 3.2.6 on 2022-06-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0004_auto_20220605_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='cp',
            field=models.CharField(choices=[('1', 'Atypical angina'), ('2', 'Typical angina'), ('3', 'Asymptomatic'), ('4', 'Non-anginal pain')], default='Atypical angina', max_length=20),
        ),
        migrations.AlterField(
            model_name='heart',
            name='slope',
            field=models.CharField(choices=[('1', 'Up Sloping'), ('2', 'Flat'), ('3', 'Down Sloping')], default='Up Sloping', max_length=15),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.CharField(choices=[('3', 'Normal'), ('6', 'Fixed Defect'), ('7', 'Reversible Defect')], default='Normal', max_length=20),
        ),
    ]
