# Generated by Django 3.2.6 on 2022-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0005_auto_20220605_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.CharField(choices=[(1, 'Male'), (0, 'Female')], default='Male', max_length=10),
        ),
    ]
