# Generated by Django 3.2.6 on 2022-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0007_alter_heart_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], default='Male'),
        ),
    ]
