# Generated by Django 3.2.6 on 2022-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0008_alter_heart_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='cp',
            field=models.IntegerField(choices=[(1, 'Atypical angina'), (2, 'Typical angina'), (3, 'Asymptomatic'), (4, 'Non-anginal pain')], default='Atypical angina'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='exang',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default='No'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='fbs',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default='False'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'ST'), (2, 'Hypertrophy')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='slope',
            field=models.IntegerField(choices=[(1, 'Up Sloping'), (2, 'Flat'), (3, 'Down Sloping')], default='Up Sloping'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.IntegerField(choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversible Defect')], default='Normal'),
        ),
    ]
