# Generated by Django 3.2.6 on 2022-06-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0009_auto_20220606_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heart',
            old_name='restbps',
            new_name='trestbps',
        ),
    ]
