# Generated by Django 3.2.6 on 2022-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0010_rename_restbps_heart_trestbps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='age',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='heart',
            name='ca',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='heart',
            name='chol',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='heart',
            name='oldpeak',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thalach',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='heart',
            name='trestbps',
            field=models.IntegerField(default=2),
        ),
    ]
