# Generated by Django 3.2.6 on 2022-06-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0011_auto_20220606_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='oldpeak',
            field=models.FloatField(default=2.0),
        ),
    ]
