# Generated by Django 3.2.6 on 2022-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0012_alter_heart_oldpeak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='cp',
            field=models.IntegerField(choices=[(0, 'Atypical angina'), (1, 'Typical angina'), (2, 'Asymptomatic'), (3, 'Non-anginal pain')], default='Atypical angina'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.IntegerField(),
        ),
    ]
