# Generated by Django 3.2.6 on 2022-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0013_auto_20220606_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='slope',
            field=models.IntegerField(choices=[(0, 'Up Sloping'), (1, 'Flat'), (2, 'Down Sloping')], default='Up Sloping'),
        ),
    ]
