# Generated by Django 3.2.6 on 2022-06-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0014_alter_heart_slope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heart',
            name='ca',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='heart',
            name='chol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heart',
            name='cp',
            field=models.IntegerField(choices=[(0, 'Atypical angina-0'), (1, 'Typical angina-1'), (2, 'Asymptomatic-2'), (3, 'Non-anginal pain-3')], default='Atypical angina-0'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='exang',
            field=models.IntegerField(choices=[(0, 'Yes- 0'), (1, 'No- 1')], default='No- 1'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='fbs',
            field=models.IntegerField(choices=[(1, 'True- 1'), (0, 'False- 0')], default='False- 0'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='oldpeak',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='heart',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'Normal- 0'), (1, 'ST- 1'), (2, 'Hypertrophy- 2')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male-1'), (0, 'Female-0')], default='Male-1'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='slope',
            field=models.IntegerField(choices=[(0, 'Up Sloping- 0'), (1, 'Flat- 1'), (2, 'Down Sloping- 2')], default='Up Sloping- 0'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thalach',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heart',
            name='trestbps',
            field=models.IntegerField(),
        ),
    ]
